#!/bin/sh
#synergia_workflow_submitter:/bin/sh
cd @@jobdir@@ && \
(time OMP_PROC_BIND=spread OMP_PLACES=cores OMP_NUM_THREADS=4 python @@script@@ @@args@@ 1> job.out 2> job.err; \
echo "synergia finished with exit status $?")
